version: "3.6"

services:
  app:
    build:
      context: ./app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    ports:
      - "5001:80"
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib:0.74.0
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317"
